"""Registre d'exemple, hors exécution."""
from __future__ import annotations

from .models import AgentProfile

DEFAULT_AGENTS: tuple[AgentProfile, ...] = (
    AgentProfile(
        id="coding-agent",
        name="Coding Agent",
        description="Corrige bugs CORS et code Python, FastAPI ou TypeScript.",
        capabilities=("coding", "python", "typescript", "review", "fastapi"),
        tags=("backend", "frontend", "bug", "api"),
        tools=("read_file", "edit_file", "run_tests"),
        permissions=("read_code", "write_code"),
        cost=0.4,
        latency=0.4,
        reliability=0.85,
        fallback_id="research-agent",
        max_actions=20,
        scope="demo",
    ),
    AgentProfile(
        id="devops-agent",
        name="DevOps Agent",
        description="Observe CI, Docker, logs et déploiements en simulation.",
        capabilities=("devops", "docker", "ci", "logs"),
        tags=("infra", "pipeline"),
        tools=("read_logs", "read_metrics"),
        permissions=("read_logs", "read_metrics"),
        cost=0.5,
        latency=0.5,
        reliability=0.8,
        fallback_id="research-agent",
        max_actions=10,
        scope="demo",
    ),
    AgentProfile(
        id="research-agent",
        name="Research Agent",
        description="Cherche dans la documentation et résume sans effet de bord.",
        capabilities=("research", "docs", "search"),
        tags=("documentation",),
        tools=("search_docs",),
        permissions=("read_docs",),
        cost=0.2,
        latency=0.3,
        reliability=0.9,
        max_actions=8,
        scope="demo",
    ),
    AgentProfile(
        id="support-agent",
        name="Support Agent",
        description="Répond au ticket client et aux questions de facturation.",
        capabilities=("support", "customer", "billing"),
        tags=("ticket", "tickets"),
        tools=("read_tickets",),
        permissions=("read_tickets",),
        cost=0.3,
        latency=0.2,
        reliability=0.75,
        max_actions=5,
        scope="demo",
    ),
    AgentProfile(
        id="security-agent",
        name="Security Agent",
        description="Audit de code et de journaux, sans élévation de droits.",
        capabilities=("security", "audit", "review"),
        tags=("audit",),
        tools=("read_code", "read_logs"),
        permissions=("read_code", "read_logs"),
        cost=0.45,
        latency=0.45,
        reliability=0.88,
        max_actions=8,
        scope="demo",
    ),
)
